# Generated by Django 5.2 on 2025-05-07 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room_delete_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
