# Generated by Django 5.2.1 on 2025-05-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('instrument', models.CharField(max_length=200)),
                ('number_of_orders', models.PositiveIntegerField()),
                ('max_price_of_orders', models.DecimalField(decimal_places=2, max_digits=20)),
                ('min_price_of_orders', models.DecimalField(decimal_places=2, max_digits=20)),
                ('average_price_of_orders', models.DecimalField(decimal_places=2, max_digits=20)),
                ('number_of_quotes', models.PositiveIntegerField()),
                ('number_of_trades', models.PositiveIntegerField()),
                ('average_price_of_trades_vwap', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_quantity_of_trades', models.PositiveIntegerField()),
                ('start_prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fixing_prices', models.DecimalField(decimal_places=2, max_digits=20)),
                ('open_interest', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
